// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTLfbCMv7ug7vRFk5VM40f57BiLfgRSPc',
    appId: '1:520692488475:web:4e61d9b2027365071edbbe',
    messagingSenderId: '520692488475',
    projectId: 'flutter-video-project',
    authDomain: 'flutter-video-project.firebaseapp.com',
    storageBucket: 'flutter-video-project.firebasestorage.app',
    measurementId: 'G-5TDZLV1D34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrDwitWG6uoCmnp9X5FqAgMUGqk-r6s7Y',
    appId: '1:520692488475:android:b1942f446057ffdf1edbbe',
    messagingSenderId: '520692488475',
    projectId: 'flutter-video-project',
    storageBucket: 'flutter-video-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnMQ0qGR4XVOWRbiSuUQOte4_ExfMsJE',
    appId: '1:520692488475:ios:1299675f27eccdc71edbbe',
    messagingSenderId: '520692488475',
    projectId: 'flutter-video-project',
    storageBucket: 'flutter-video-project.firebasestorage.app',
    iosBundleId: 'com.thinkzonellc.flutterVideoDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnMQ0qGR4XVOWRbiSuUQOte4_ExfMsJE',
    appId: '1:520692488475:ios:d2b312d46d6995741edbbe',
    messagingSenderId: '520692488475',
    projectId: 'flutter-video-project',
    storageBucket: 'flutter-video-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterVideoDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTLfbCMv7ug7vRFk5VM40f57BiLfgRSPc',
    appId: '1:520692488475:web:30193be1e05145181edbbe',
    messagingSenderId: '520692488475',
    projectId: 'flutter-video-project',
    authDomain: 'flutter-video-project.firebaseapp.com',
    storageBucket: 'flutter-video-project.firebasestorage.app',
    measurementId: 'G-4NBFCH098W',
  );

}